name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger the workflow on version tags (e.g., v1.0.0)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --noconsole --name MarkIt --icon=markit_icon.ico --onefile gui\gui.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MarkIt
        path: dist/MarkIt.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: MarkIt
        path: dist

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/MarkIt.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}